# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e962de78212cc81ae4c76e08ab0fcea6e38558ad25575c3afaf24a1b00fc9756ec5fe45b3c85cc2a2943835cf77928e361bd2a819650ceca35987cffd0f59ddb

test:
  secret_key_base: 8f31610a3220e03c8b4fbb165c7e3b49cf5f1026e0628ef5b2887e487afda9974e7c29354bd39086afad4271cafb482c2016891d89bf4de77fa0268a24fa64c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
